version: '3.8'
services:
  svelte-frontend:
    build: .
    container_name: svelte-app
    ports:
      # Bạn ông xài cổng nào rồi thì ông chọn số khác (ví dụ: 8081)
      - '8081:80'
    environment:
      - API_TARGET=http://100.102.69.100:3000
    restart: always
